# Generated by Django 3.1.4 on 2021-08-21 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(db_column='log_id', max_length=20)),
                ('login_passwd', models.CharField(db_column='passwd', max_length=120)),
            ],
            options={
                'db_table': 'tb_super',
            },
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('notfn_id', models.AutoField(db_column='notfn_id', primary_key=True, serialize=False)),
                ('notfn_date', models.DateField(db_column='notfn_date')),
                ('notfn_title', models.CharField(db_column='notfn_title', default='', max_length=120)),
                ('notfn_content', models.CharField(db_column='notfn_content', max_length=255)),
            ],
            options={
                'db_table': 'tb_notfn',
            },
        ),
        migrations.CreateModel(
            name='SportsDetail',
            fields=[
                ('sport_id', models.AutoField(db_column='sp_id', primary_key=True, serialize=False)),
                ('sport_name', models.CharField(db_column='sp_name', max_length=50)),
                ('sport_type', models.CharField(choices=[('m', 'Men'), ('w', 'Women')], db_column='sp_type', max_length=10)),
            ],
            options={
                'db_table': 'tb_sports',
            },
        ),
        migrations.CreateModel(
            name='TeamDetails',
            fields=[
                ('team_id', models.AutoField(db_column='t_id', primary_key=True, serialize=False)),
                ('team_name', models.CharField(db_column='t_name', max_length=50)),
                ('team_place', models.CharField(db_column='t_place', max_length=50)),
                ('team_email', models.EmailField(db_column='tb_mail', max_length=100)),
                ('team_phno', models.CharField(db_column='t_ph', max_length=10)),
                ('team_user_id', models.IntegerField()),
                ('team_logo', models.ImageField(db_column='t_logo', upload_to='Team/')),
                ('team_passwd', models.CharField(db_column='t_pswd', max_length=120)),
                ('team_status', models.CharField(db_column='t_status', max_length=20)),
                ('team_type', models.ForeignKey(db_column='t_type', on_delete=django.db.models.deletion.CASCADE, to='ClubManagementApp.sportsdetail')),
            ],
            options={
                'db_table': 'tb_team',
            },
        ),
        migrations.CreateModel(
            name='PlayerDetails',
            fields=[
                ('player_id', models.AutoField(db_column='p_id', primary_key=True, serialize=False)),
                ('player_name', models.CharField(db_column='p_name', max_length=20)),
                ('player_position', models.CharField(db_column='p_pos', max_length=20)),
                ('player_address', models.CharField(db_column='p_addr', max_length=200)),
                ('player_dob', models.CharField(db_column='p_dob', max_length=20)),
                ('player_email', models.EmailField(db_column='p_email', max_length=254)),
                ('player_img', models.ImageField(db_column='p_img', upload_to='Player/')),
                ('player_height', models.IntegerField(db_column='p_height', default=0)),
                ('player_weight', models.IntegerField(db_column='p_weight', default=0)),
                ('player_ph', models.CharField(db_column='p_ph', max_length=10)),
                ('player_passwd', models.CharField(db_column='p_pswd', max_length=120)),
                ('team_id', models.ForeignKey(db_column='t_id', on_delete=django.db.models.deletion.CASCADE, to='ClubManagementApp.teamdetails')),
            ],
            options={
                'db_table': 'tb_players',
            },
        ),
    ]
