# Generated by Django 3.1.4 on 2021-08-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueDetails',
            fields=[
                ('venue_id', models.AutoField(db_column='v_id', primary_key=True, serialize=False)),
                ('venue_name', models.CharField(db_column='v_name', max_length=30)),
                ('venue_type', models.CharField(db_column='v_type', max_length=20)),
                ('venue_address', models.CharField(db_column='v_address', max_length=200)),
                ('venue_contact', models.CharField(db_column='v_contact', max_length=10)),
                ('venue_email', models.CharField(db_column='v_email', max_length=30)),
                ('venue_user_id', models.IntegerField(db_column='v_userid')),
                ('venue_pic', models.ImageField(db_column='v_pic', upload_to='Venue/')),
                ('venue_seat', models.ImageField(db_column='v_seat', upload_to='Venue/Seat/')),
                ('venue_passwd', models.CharField(db_column='v_passwd', max_length=20)),
                ('venue_status', models.CharField(db_column='v_status', max_length=10)),
            ],
            options={
                'db_table': 'tb_venue',
            },
        ),
    ]
