# Generated by Django 3.1.4 on 2021-08-23 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClubManagementApp', '0002_venuedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_title', models.CharField(db_column='b_title', max_length=20)),
                ('amount', models.FloatField(db_column='amt')),
                ('total_seats', models.IntegerField(db_column='seats')),
                ('venue_id', models.ForeignKey(db_column='v_id', on_delete=django.db.models.deletion.CASCADE, to='ClubManagementApp.venuedetails')),
            ],
            options={
                'db_table': 'tb_block',
            },
        ),
    ]
