# Generated by Django 3.1.4 on 2021-08-23 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClubManagementApp', '0003_blockdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentDetails',
            fields=[
                ('tournament_id', models.AutoField(db_column='t_id', primary_key=True, serialize=False)),
                ('tournament_title', models.CharField(db_column='t_title', max_length=20)),
                ('players_allowed', models.IntegerField(db_column='max_players')),
                ('start_date', models.CharField(db_column='s_date', max_length=20)),
                ('end_date', models.CharField(db_column='e_date', max_length=20)),
                ('reg_date', models.CharField(db_column='reg_date', max_length=20)),
                ('reg_fee', models.FloatField(db_column='reg_fee')),
                ('win_prize', models.FloatField(db_column='win_prize')),
                ('venue_approval', models.CharField(db_column='v_approval', max_length=20)),
                ('tournament_status', models.CharField(db_column='t_status', max_length=20)),
                ('sport_type', models.ForeignKey(db_column='s_type', on_delete=django.db.models.deletion.CASCADE, to='ClubManagementApp.sportsdetail')),
                ('venue_id', models.ForeignKey(db_column='v_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ClubManagementApp.venuedetails')),
            ],
            options={
                'db_table': 'tb_tournament',
            },
        ),
    ]
