# Generated by Django 3.1.4 on 2022-02-20 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClubManagementApp', '0005_remove_tournamentdetails_venue_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentPlayers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_status', models.CharField(default='not approved', max_length=20)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubManagementApp.playerdetails')),
                ('tournament_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ClubManagementApp.tournamentdetails')),
            ],
            options={
                'db_table': 'tb_tournamentPlayers',
            },
        ),
    ]
