# Generated by Django 3.1.4 on 2022-02-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubManagementApp', '0006_tournamentplayers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayers',
            name='cert',
            field=models.FileField(default='Players/Certificates', upload_to=''),
        ),
    ]
