# Generated by Django 3.1.4 on 2022-02-20 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClubManagementApp', '0007_tournamentplayers_cert'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayers',
            name='team_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ClubManagementApp.teamdetails'),
        ),
    ]
