# Generated by Django 3.1.4 on 2022-02-20 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClubManagementApp', '0008_tournamentplayers_team_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_status', models.CharField(default='not approved', max_length=20)),
                ('team_point', models.IntegerField(default=0)),
                ('team_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ClubManagementApp.teamdetails')),
                ('tournament_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ClubManagementApp.tournamentdetails')),
            ],
            options={
                'db_table': 'tb_tournamentReg',
            },
        ),
    ]
