# Generated by Django 4.0.3 on 2022-04-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubManagementApp', '0009_tournamentregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='notfn_date',
            field=models.CharField(db_column='notfn_date', default='', max_length=20),
        ),
    ]
