# Generated by Django 4.0.3 on 2022-04-17 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClubManagementApp', '0011_fixture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fixture',
        ),
    ]
