# Generated by Django 4.0.3 on 2022-04-17 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClubManagementApp', '0012_delete_fixture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('team1_score', models.CharField(max_length=10)),
                ('team2_score', models.CharField(max_length=10)),
                ('result', models.CharField(max_length=30)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='ClubManagementApp.teamdetails')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='ClubManagementApp.teamdetails')),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubManagementApp.tournamentdetails')),
            ],
            options={
                'db_table': 'tb_fixture',
            },
        ),
    ]
