# Generated by Django 4.0.3 on 2022-04-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubManagementApp', '0014_alter_fixture_team1_alter_fixture_team2'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='match_video',
            field=models.FileField(default='', upload_to='', verbose_name='video/'),
        ),
    ]
