# Generated by Django 4.0.3 on 2022-04-18 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClubManagementApp', '0015_fixture_match_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentdetails',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ClubManagementApp.teamdetails'),
        ),
    ]
