# Generated by Django 4.0.3 on 2022-04-19 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClubManagementApp', '0016_tournamentdetails_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='team1',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='ClubManagementApp.teamdetails'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='team2',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='ClubManagementApp.teamdetails'),
        ),
    ]
