# Generated by Django 4.0.3 on 2022-04-24 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClubManagementApp', '0020_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('tickets', models.IntegerField()),
                ('total', models.FloatField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubManagementApp.blockdetails')),
                ('fix_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubManagementApp.fixture')),
                ('m_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubManagementApp.memberdetails')),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubManagementApp.tournamentdetails')),
            ],
            options={
                'db_table': 'tb_booking',
            },
        ),
    ]
