# Generated by Django 4.0.3 on 2022-04-24 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClubManagementApp', '0021_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
