# Generated by Django 4.0.3 on 2022-04-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubManagementApp', '0024_alter_booking_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='tickets',
            field=models.IntegerField(default=0),
        ),
    ]
