# Generated by Django 4.0.3 on 2022-04-24 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClubManagementApp', '0026_booking_book_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField()),
                ('fix_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubManagementApp.fixture')),
                ('m_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubManagementApp.memberdetails')),
            ],
            options={
                'db_table': 'tb_vote',
            },
        ),
    ]
