from ClubManagementApp.views import VenueView
from django.urls import path
from  .views import CommonView,AdminView,UsersView,PlayersView,TeamView

app_name="club_management"


urlpatterns=[
    path('',CommonView.ProjectHome,name="home"),
    path('AdminData',CommonView.AdminData),
    path('Admin/PendingTeam',AdminView.PendingTeamRequest,name="team_request"),
    path('Admin/PendingVenue',AdminView.PendingVenueRequest,name="venue_request"),
    path('Admin/AddTournament',AdminView.AddTournament,name="add_tournament"),
    path('AdminHome/ViewBlock/<int:venue_id>',AdminView.ViewBlock,name="view_block"),
    path('AdminHome/GetVenue',AdminView.getVenue,name="get_venue"),
    path('AdminHome/ViewPlayers/<int:team_id>',AdminView.ViewPlayers,name="view_players"),
    path('Admin/ViewTeams',AdminView.ViewTeams,name="view_teams"),
    path('Admin/ViewVenue',AdminView.ViewVenue,name="view_venue"),
    path('Admin/ApproveTeam/<int:id>',AdminView.ApproveTeam,name="approve_team"),
    path('Admin/RejectTeam/<int:id>',AdminView.RejectTeam,name="reject_team"),
    path('Admin/TournamentRequest',AdminView.TournamentRequest,name="t_request"),
    path('Admin/ApproveVenue/<int:id>',AdminView.ApproveVenue,name="approve_venue"),
    path('Admin/RejectVenue/<int:id>',AdminView.RejectVenue,name="reject_venue"),
    path('Login',CommonView.Login,name="login"),
    path('AdminHome/Fixture',AdminView.GenerateFixture,name="gen_fixture"),
    path('AdminHome',AdminView.AdminHome,name="admin_home"),
    path('AdminHome/AddSports',AdminView.AddSport,name="add_sport"),
    path('AdminHome/Notification',AdminView.AddNotification,name="add_notification"),
    path('TeamReg',CommonView.TeamReg,name="team_reg"),
    path('PlayerHome',PlayersView.PlayerHome,name="player_home"),
    path('TeamHome',TeamView.TeamHome,name="team_home"),
    path('TeamHome/ViewPlayers',TeamView.ViewPlayers,name="view_players"),
    path('TeamHome/Tournaments',TeamView.ViewTournaments,name="ta_view_tournaments"),
    path('TeamHome/TRegistered',TeamView.RegisteredTournaments,name="ta_treg"),
    path('TeamHome/Previous',TeamView.PreviousMatches,name="ta_prev"),
    path('Admin/TrTeams',AdminView.TournamentTeams,name="a_trTeam"),
    path('Admin/ViewTrTeam',AdminView.ViewTournamentPlayers,name="a_viewtrTeam"),
    path('Admin/UpdatePlayer',AdminView.UpdatePlayerStatus,name="a_updpl"),
    path('TeamAdmin/Fixtures/<int:tid>',TeamView.Fixtures), 
    path('TeamAdmin/LiveMatch/<int:tid>',TeamView.LiveMatch), 
    path('TeamAdmin/PointTable/<int:tid>',TeamView.PointsTable), 
    path('TeamAdmin/MatchStatus/<int:tid>',TeamView.MatchStatus), 
    path('TeamHome/T-Players/<int:id>',TeamView.AddTournamentPlayers,name="t_players"),
    path('TeamHome/Edit/<int:id>',TeamView.EditPlayer,name="edit_player"),
    path('TeamHome/Del/<int:id>',TeamView.DeletePlayer,name="delete_player"),
    path('TeamHome/View/<int:id>',TeamView.ViewPlayer,name="view_player"),
    path('TeamHome/Tournament/<int:t_id>',TeamView.TournamentDetail,name="ta_tdetail"),
    path('TeamHome/Logout',TeamView.Logout,name="logout"),
    path('Team/AddPlayer',TeamView.AddPlayer,name='add_player'),
    path('RegisterVenue',CommonView.VenueReg,name="venue_reg"),
    path('VenueHome',VenueView.VenueHome,name="venue_home"),
    path('VenueHome/Block',VenueView.ViewBlock,name="view_block"),
    path('VenueHome/Booking',VenueView.ViewBooking,name="view_booking"),
    path('VenueHome/AddBlock',VenueView.AddBlock,name="add_block"),
    path('VenueHome/Password',VenueView.ChangePassword,name="va_change_pass"),
    path('VenueHome/VenueReq',VenueView.VenueRequest,name="v_req"),
    path('VenueHome/Reason',VenueView.RejectReason,name="r_reason")
]